### ISSUE TITLE
Running docker image fails to create master key

### ISSUE THREAD

**Issue by Beanow** [jfrog/artifactory-docker-examples#137]
The default settings don't use the documented volume to generate the master key.

Note it attempts to write to `/opt/jfrog/artifactory/etc/security` but should be `/var/opt/jfrog/artifactory/etc/security`.

```

Caused by: java.lang.RuntimeException: Could not save master key.
	at org.jfrog.security.masterkey.MasterKeyUtils.saveMasterKeyToFile(MasterKeyUtils.java:32)
	at org.jfrog.security.masterkey.MasterKeyBootstrapper.saveAndSecureMasterKey(MasterKeyBootstrapper.java:150)
	at org.jfrog.security.masterkey.MasterKeyBootstrapper.handleMasterKey(MasterKeyBootstrapper.java:38)
	at org.jfrog.access.server.startup.AccessStartupService.init(AccessStartupService.java:37)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:366)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:311)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:134)
	... 111 more
Caused by: java.nio.file.FileSystemException: /opt/jfrog/artifactory/etc/security: Operation not permitted
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:91)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileAttributeViews$Posix.setMode(UnixFileAttributeViews.java:238)
	at sun.nio.fs.UnixFileAttributeViews$Posix.setPermissions(UnixFileAttributeViews.java:260)
	at java.nio.file.Files.setPosixFilePermissions(Files.java:2045)
	at org.jfrog.security.file.SecurityFolderHelper.setPermissionsOnSecurityFolder(SecurityFolderHelper.java:282)
	at org.jfrog.security.file.SecurityFolderHelper.setPermissionsOnSecurityFile(SecurityFolderHelper.java:309)
	at org.jfrog.security.masterkey.MasterKeyUtils.saveMasterKeyToFile(MasterKeyUtils.java:30)
	... 121 more
```

Using stack file:
```
# Deployed with portainer as "shared_artifactory"
version: '3.4'
services:
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:6.6.5
    volumes:
      - artifactory-data:/var/opt/jfrog/artifactory

volumes:
  artifactory-data:
```

**Comment by Beanow** [comment]
I believe the issue here lies with the Azure file storage. It uses smb/cifs under the hood and has incomplete support for file permissions.

**Comment by JfrogPrasanna** [comment]
Closing this. Please open a ticket if this exists in 7.x versions. Review  new version [here.](https://www.jfrog.com/confluence/display/JFROG/Installing+Artifactory#InstallingArtifactory-DockerComposeInstallation)
