### ISSUE TITLE
Artifactory failed to initialize: Context is null

### ISSUE THREAD

**Issue by saivikas408** [jfrog/artifactory-docker-examples#188]
Hi All,

Need help for fixing this issue .I am running artifactory as container  ,version 6.14.2

I am getting this error in logs :  
```
artifactory_1   | Caused by: java.lang.RuntimeException: The current Artifactory config schema namespace is 'http://artifactory.jfrog.org/xsd/2.2.3' The provided config does not seem to be compliant with it.
artifactory_1   | The auto discovery of Artifactory configuration version did not find any valid version for the artifactory.config.xml file.
artifactory_1   | Please fix this file manually!
artifactory_1   |       at org.artifactory.descriptor.reader.CentralConfigReader.verifyCurrentConfigVersion(CentralConfigReader.java:96)
artifactory_1   |       at org.artifactory.descriptor.reader.CentralConfigReader.readAndConvert(CentralConfigReader.java:68)
artifactory_1   |       at org.artifactory.config.CentralConfigServiceImpl.getCurrentConfig(CentralConfigServiceImpl.java:292)
artifactory_1   |       at org.artifactory.config.CentralConfigServiceImpl.initCacheAndGetCurrent(CentralConfigServiceImpl.java:158)
artifactory_1   |       at org.artifactory.config.CentralConfigServiceImpl.convert(CentralConfigServiceImpl.java:206)
artifactory_1   |       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
artifactory_1   |       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
artifactory_1   |       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
artifactory_1   |       at java.base/java.lang.reflect.Method.invoke(Method.java:566)
artifactory_1   |       at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:343)
artifactory_1   |       at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:206)
artifactory_1   |       at com.sun.proxy.$Proxy54.convert(Unknown Source)
artifactory_1   |       at org.artifactory.converter.ConvertersManagerImpl.serviceConvert(ConvertersManagerImpl.java:167)
artifactory_1   |       ... 9 common frames omitted
artifactory_1   | 2020-02-07 15:31:39,145 [http-nio-8081-exec-1] [ERROR] (o.a.w.s.ArtifactoryFilter:194) - Artifactory failed to initialize: Context is null
```

and the below error when I hit the artifactory url
```
{
  "errors" : [ {
    "status" : 500,
    "message" : "Artifactory failed to initialize: check Artifactory logs for errors."
  } ]
}
```

**Comment by eldada** [comment]
@saivikas408 - can you provide more details? It seems you have a bad config. Can it be you are using old configuration (left behind from another installation)?
First - make sure to start with clean volumes. They might have leftover config conflicting with your Artifactory.
Second - provide us with details on how to reproduce.

**Comment by JfrogPrasanna** [comment]
closing due to inactivity.

**Comment by mmckinn6** [comment]
I have the same issue. All configs are untouched. Just performed yum update and Artifactoy 7.4 was installed. i went from 6.19

**Comment by mmckinn6** [comment]
I have had lots of issues with artifactory 7 upgrades.

**Comment by jfrog-aparicio** [comment]
There is a bug where you can't upgrade from 6.19 to 7.x unless you upgrade to 7.4.3+

**Comment by mmckinn6** [comment]
Unfortunately, I was still unable to get 7.3 working. It seems to be derby related and the logs are saying the db is read only among other errors within the shell scripts installed

**Comment by mmckinn6** [comment]
*7.4.3

**Comment by JfrogPrasanna** [comment]
@mmckinn6 Can you please share more details:  
1. Do you are seeing with exception in logs? Please share them here
2. Also can you  give info on what you upgraded from what ? Is it 6.19 in rpm to 7.4.3 rpm installer?  3. Please send us the migration.log and see if there are any issue in migration of properties.
4 Please also send us the `system.yaml` to see the old properties are indeed there.

**Comment by JfrogPrasanna** [comment]
closing due to inactivity.
