### ISSUE TITLE
Artifactory pro 7.2.1 installation is failing with artifactory-pro.yaml

### ISSUE THREAD

**Issue by lakshmanavinod** [jfrog/artifactory-docker-examples#192]
I am facing the below issue , while installing artifactory pro with version 7.2.1 with postgresql db version 9.6.11
```
artifactory    | 2020-03-10T12:34:22.059Z [jfac ] [ERROR] [d68bda19187bd72 ] [o.j.s.u.DbStatementUtils:66   ] [ocalhost-startStop-1] - ****Failed to execute query: TYPE 'BYTEA' does not exist.:****
artifactory    | CREATE TABLE access_permissions_custom_data (
artifactory    |   perm_id    BIGINT   NOT NULL,
artifactory    |   data       BYTEA    NOT NULL,
artifactory    |   CONSTRAINT access_perm_data_pk PRIMARY KEY (perm_id),
artifactory    |   CONSTRAINT access_perm_data_perms_fk FOREIGN KEY (perm_id) REFERENCES access_permissions (perm_id)
artifactory    | )
artifactory    | 2020-03-10T12:34:22.069Z [jfac ] [ERROR] [d68bda19187bd72 ] [.s.d.u.AccessJdbcHelperImpl:66] [ocalhost-startStop-1] - Could not initialize database:
artifactory    | java.lang.IllegalStateException: Could not initialize database: TYPE 'BYTEA' does not exist.
artifactory    |        at org.jfrog.access.server.db.util.AccessJdbcHelperImpl.initDb(AccessJdbcHelperImpl.java:127)
artifactory    |        at org.jfrog.access.server.db.util.AccessJdbcHelperImpl.init(AccessJdbcHelperImpl.java:60)
artifactory    |        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
artifactory    |        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
artifactory    |        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
artifactory   
```
Steps to reproduce:
============
1. I have centos 7.7 linux vm with git,docker,docker-compose installed.
2. git clone https://github.com/jfrog/artifactory-docker-examples.git
3. cd artifactory-docker-examples/docker-compose/artifactory
4. sudo  ./prepareHostEnv.sh -t pro -c
5. sudo docker-compose -f artifactory-pro.yml up -d

I have tried the same with Artifactory version 6.17.0 and there are no issues.

**Comment by eldada** [comment]
Hi @lakshmanavinod . This repository is deprecated.
You should use the new Docker compose installer we have in our [official documentation](https://www.jfrog.com/confluence/display/JFROG/Installing+Artifactory#InstallingArtifactory-DockerComposeInstallation).
