### ISSUE TITLE
Artifactory in docker container crashes on second (!) run

### ISSUE THREAD

**Issue by ealebed** [jfrog/artifactory-docker-examples#89]
Hi all!
I try start artifactory in docker using docker-compose file:

```
version: '3'
networks:
  jfrog_net:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16

services:
  artifactory:
    image: docker.bintray.io/jfrog/artifactory-oss:6.1.0
    container_name: artifactory
    restart: always
    ports:
     - 8080:8081
    volumes:
     - ../artifactory:/var/opt/jfrog/artifactory
     - ../artifactory.config.import.xml:/var/opt/jfrog/artifactory/etc/artifactory.config.import.xml
    networks:
      jfrog_net:
        ipv4_address: "172.20.0.5"
```

At first run all works fine, but if I execute `docker-compose down` and than `docker-compose up -d`, docker container looks working:
```
docker container ls
CONTAINER ID        IMAGE                                           COMMAND                  CREATED             STATUS              PORTS                    NAMES
62c2b1707bb1        docker.bintray.io/jfrog/artifactory-oss:6.1.0   "/entrypoint-artifac…"   5 seconds ago       Up 4 seconds        0.0.0.0:8080->8081/tcp   artifactory
```

but artifactory not working:
```
curl -XGET 'http://localhost:8080/artifactory/api/repositories'
{
  "errors" : [ {
    "status" : 500,
    "message" : "Artifactory failed to initialize: check Artifactory logs for errors."
  } ]
}%
```

In logs (`docker logs -f artifactory`) I see next:
```
...
2018-07-03 12:07:39,701 [art-init] [INFO ] (o.j.s.c.EncryptionWrapperFactory:33) - createArtifactoryKeyWrapper  EncryptionWrapperBase{ encodingType=ARTIFACTORY_MASTER, topEncrypter=BytesEncrypterBase{ Cipher='AES128',  keyId='23Xpx'}, formatUsed=DotFormat, decrypters=[BytesEncrypterBase{ Cipher='AES128',  keyId='23Xpx'}]}
2018-07-03 12:07:39,743 [art-init] [ERROR] (o.j.s.c.EncryptionWrapperBase:185) - no matched algorithm and key for AES128 z5R8K
2018-07-03 12:07:39,751 [art-init] [ERROR] (o.a.w.s.ArtifactoryContextConfigListener:92) - Application could not be initialized: no matched algorithm and key forAES128 z5R8K
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.artifactory.webapp.servlet.ArtifactoryContextConfigListener.configure(ArtifactoryContextConfigListener.java:207)
	at org.artifactory.webapp.servlet.ArtifactoryContextConfigListener.access$200(ArtifactoryContextConfigListener.java:63)
	at org.artifactory.webapp.servlet.ArtifactoryContextConfigListener$1.run(ArtifactoryContextConfigListener.java:88)
Caused by: org.springframework.beans.factory.BeanInitializationException: Failed to initialize bean 'org.artifactory.config.InternalCentralConfigService'.; nested exception is org.jfrog.security.crypto.exception.CryptoRuntimeException: org.jfrog.security.crypto.KeyIdAlgCipherNotFound: no matched algorithm and key forAES128 z5R8K
	at org.artifactory.spring.ArtifactoryApplicationContext.refresh(ArtifactoryApplicationContext.java:253)
	at org.artifactory.spring.ArtifactoryApplicationContext.<init>(ArtifactoryApplicationContext.java:136)
	... 7 common frames omitted
Caused by: org.jfrog.security.crypto.exception.CryptoRuntimeException: org.jfrog.security.crypto.KeyIdAlgCipherNotFound: no matched algorithm and key forAES128 z5R8K
	at org.jfrog.security.crypto.EncryptionWrapperBase.decryptFallback(EncryptionWrapperBase.java:195)
	at org.jfrog.security.crypto.EncryptionWrapperBase.decrypt(EncryptionWrapperBase.java:129)
	at org.jfrog.security.crypto.EncryptionWrapperBase.decrypt(EncryptionWrapperBase.java:115)
	at org.jfrog.security.crypto.EncryptionWrapperBase.decrypt(EncryptionWrapperBase.java:101)
	at org.jfrog.security.crypto.EncryptionWrapperBase.decryptIfNeeded(EncryptionWrapperBase.java:92)
	at org.jfrog.security.crypto.EncryptionWrapperBase.encryptIfNeeded(EncryptionWrapperBase.java:253)
	at org.artifactory.common.crypto.CryptoHelper.encryptIfNeeded(CryptoHelper.java:73)
	at org.artifactory.layout.EncryptConfigurationInterceptor.getNewPassword(EncryptConfigurationInterceptor.java:181)
	at org.artifactory.layout.EncryptConfigurationInterceptor.encryptOrDecrypt(EncryptConfigurationInterceptor.java:171)
	at org.artifactory.layout.EncryptConfigurationInterceptor.encrypt(EncryptConfigurationInterceptor.java:203)
	at org.artifactory.layout.EncryptConfigurationInterceptor.onBeforeSave(EncryptConfigurationInterceptor.java:193)
	at org.artifactory.config.ConfigurationChangesInterceptorsImpl.onBeforeSave(ConfigurationChangesInterceptorsImpl.java:43)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:201)
	at com.sun.proxy.$Proxy119.onBeforeSave(Unknown Source)
	at org.artifactory.config.CentralConfigServiceImpl.preSaveDescriptor(CentralConfigServiceImpl.java:319)
	at org.artifactory.config.CentralConfigServiceImpl.forceSaveDescriptorInternal(CentralConfigServiceImpl.java:377)
	at org.artifactory.config.CentralConfigServiceImpl.initCacheAndGetCurrent(CentralConfigServiceImpl.java:166)
	at org.artifactory.config.CentralConfigServiceImpl.init(CentralConfigServiceImpl.java:147)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.support.AopUtils.invokeJoinpointUsingReflection(AopUtils.java:317)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.invokeJoinpoint(ReflectiveMethodInvocation.java:190)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:99)
	at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:281)
	at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:96)
	at org.artifactory.storage.fs.lock.aop.LockingAdvice.invoke(LockingAdvice.java:76)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:207)
	at com.sun.proxy.$Proxy120.init(Unknown Source)
	at org.artifactory.spring.ArtifactoryApplicationContext.refresh(ArtifactoryApplicationContext.java:251)
	... 8 common frames omitted
Caused by: org.jfrog.security.crypto.KeyIdAlgCipherNotFound: no matched algorithm and key forAES128 z5R8K
	at org.jfrog.security.crypto.EncryptionWrapperBase.decryptFallback(EncryptionWrapperBase.java:186)
	... 45 common frames omitted
...
```

If needed, I can attach full log or file `/artifactory.config.import.xml`

**Comment by mfuxi** [comment]
Looks like an issue with your certificate.
Did you generate some self signed certificate or is it the example certificate that comes with the repo?

**Comment by ealebed** [comment]
Thanks, @mfuxi 

No, I didn't generate any certificates.
Maybe it is some cert that comes with docker image or autogenerated (when container first run) certificate?

**Comment by ealebed** [comment]
Oh, I think I find solution!

In my `artifactory.config.import.xml` I just remove 
```
...
            <adminToken>.........</adminToken>
...
```

and now it works fine!

Sorry )

**Comment by eselvam** [comment]
sometimes, it could be a key issue in the backend db.  the cipher Cipher='AES128',  keyId='23Xpx, i.e. the cipher is used to encrypt it and when artifactory try to decrypt, it uses the key to decrypt. If you don't have right key, then you will face this issue.  Please check the key in backend db in specific table and delete the key. once deleted, restart the artifactory, it should work.
